# Generated by Django 4.1 on 2024-11-30 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refbook',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='refbookelement',
            name='refbook_version_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.refbookversion', verbose_name='Версия справочника'),
        ),
        migrations.AlterField(
            model_name='refbookversion',
            name='refbook_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.refbook', verbose_name='Cправочник'),
        ),
    ]
