# Generated by Django 5.1.3 on 2024-11-27 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='CatalogVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('catalog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.catalog')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=300)),
                ('catalog_version_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.catalogversion')),
            ],
        ),
    ]
