# Generated by Django 4.1 on 2024-11-28 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_catalog_code_catalogversion_catalogelement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalog',
            options={'verbose_name': 'Справочник', 'verbose_name_plural': 'Справочники'},
        ),
        migrations.AlterModelOptions(
            name='catalogelement',
            options={'verbose_name': 'Элемент справочника', 'verbose_name_plural': 'Элементы справочника'},
        ),
        migrations.AlterModelOptions(
            name='catalogversion',
            options={'verbose_name': 'Версия справочника', 'verbose_name_plural': 'Версии справочника'},
        ),
        migrations.AlterField(
            model_name='catalog',
            name='code',
            field=models.CharField(max_length=100, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='catalogelement',
            name='catalog_version_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.catalogversion', verbose_name='Идентификатор версии справочника'),
        ),
        migrations.AlterField(
            model_name='catalogelement',
            name='code',
            field=models.CharField(max_length=100, verbose_name='Код элемента'),
        ),
        migrations.AlterField(
            model_name='catalogelement',
            name='value',
            field=models.CharField(max_length=300, verbose_name='Значение элемента'),
        ),
        migrations.AlterField(
            model_name='catalogversion',
            name='catalog_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.catalog', verbose_name='Идентификатор справочника'),
        ),
        migrations.AlterField(
            model_name='catalogversion',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала действия версии'),
        ),
        migrations.AlterField(
            model_name='catalogversion',
            name='version',
            field=models.CharField(max_length=50, verbose_name='Версия'),
        ),
    ]
