# Generated by Django 4.1 on 2024-12-01 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_rename_refbook_id_refbookversion_refbook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refbookelement',
            old_name='refbook_version_id',
            new_name='refbook_version',
        ),
        migrations.AlterUniqueTogether(
            name='refbookelement',
            unique_together={('refbook_version', 'code')},
        ),
    ]
